### ISSUE TITLE
What do you mean by sql file in readme?

### ISSUE THREAD

**Issue by hadifar** [motazsaad/WikiDocsAligner#2]
Hi,

Thanks for releasing this toolkit. Would you please give an example of how to run your script? I don't know what do mean by SQL file. I looked into the nlwiki pages and it contains multiple SQL file:
https://dumps.wikimedia.org/nlwiki/20201201/

Can you give an example or update readme how to run your script? 

Many Thanks

**Comment by motazsaad** [comment]
Hi, 
You can get the sql file from 
https://dumps.wikimedia.org/nlwiki/latest/nlwiki-latest-langlinks.sql.gz 
or 
https://dumps.wikimedia.org/nlwiki/20201201/nlwiki-20201201-langlinks.sql.gz

I hope this helps
